## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW2_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
#Q1
import pandas as pd
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

#Q1 - 1 
names = pd.DataFrame(data)
print ("Here is a dataframe for our Data:\n",names)

#Q1 - 2

cond_psych = names ["job"]  ==  "psychologist"
cond_teach = names["job"] == "teacher"
cond_cars = names["num_cars"] > names["family_size"]

question2 = names.loc[(cond_psych | cond_teach) & cond_cars]
print("\nHere is a list of people that are either psychologists or teachers\n and their number of cars is greater than their family size:\n ",question2, "\n")

#Q1 - 3
fam_size = names["family_size"] <= 2
num_cars = names["num_cars"] >= 1

question3 = names.loc[fam_size & num_cars]
print("\nHere is a list of people who have at most 2 family members and at least 1 car:\n", question3, "\n")

#Q1 - 4
no_dupe = names.loc[:, "job"].drop_duplicates()
print("Here is a list of all the unique jobs in this dataset:\n",no_dupe)


Here is a dataframe for our Data:
      name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1

Here is a list of people that are either psychologists or teachers
 and their number of cars is greater than their family size:
     name           job  family_size  num_cars
5  Lisa  psychologist            3         4 


Here is a list of people who have at most 2 family members and at least 1 car:
     name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2        

**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
# Q2

import pandas as pd
import numpy as np

fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

df = pd.DataFrame({"Fruits": fruit, "Weights": weights})
df_mean = df.groupby("Fruits").mean()
print(df_mean)


        Weights
Fruits         
apple       6.5
banana      5.2
carrot      3.0


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
# Q3

import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

# Q3-1.
i = np.argsort(course_name)
print("Indices of the sorted elements of course_name array: ")
print(i, "\n")

# Q3-2
print(np.char.startswith(course_name, "P"))

Indices of the sorted elements of course_name array: 
[1 3 0 2 4] 

[ True False False  True False]


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
#Q4

import numpy as np

student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

# Q4-1
print("Orignal Array:",student_id)
print("Reversed Array:",student_id[::-1])

# Q4-2
sorted_students = np.sort(student_id)
print("3 of the largest values:",sorted_students[-3:])

Orignal Array: [1023 5202 6230 1671 1682 5241 4532]
Reversed Array: [4532 5241 1682 1671 6230 5202 1023]
3 of the largest values: [5202 5241 6230]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [12]:
import numpy as np

x = np.arange(1, 100)
n =(x[(x % 3 == 0) | (x % 5 == 0)])
print("Here are all the multiples of 3 and 5 under 100:\n",n[:])
print("\nHere is the sum of all the numbers listed ablove:\n",n.sum())

Here are all the multiples of 3 and 5 under 100:
 [ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]

Here is the sum of all the numbers listed ablove:
 2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

In [2]:
import numpy as np

# Q6
arr = np.arange(12).reshape(3,4)
print("Orignal Array:\n",arr, "\n")

# Q6 -1
column = arr[:, [1]]
arr[:, [1]] = arr[:, [2]]
arr[:, [2]] = column
print("Swapped Column 1 with 2:\n",arr, "\n")

# Q6
row = arr[[0], :]
arr[[0], :] = arr[[1], :]
arr[[1], :] = row
print("Swapped Row 0 with 1:\n",arr,"\n")

print("Note: Columns and Rows start from 0")

Orignal Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Swapped Column 1 with 2:
 [[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]] 

Swapped Row 0 with 1:
 [[ 4  6  5  7]
 [ 0  2  1  3]
 [ 8 10  9 11]] 

Note: Columns and Rows start from 0
